### ISSUE TITLE
Significant Race Effects.

### ISSUE THREAD

**Issue by jlhanson5** [bids-apps/baracus#10]
Hello all,

I just wanted to give a heads up... in a slightly diverse sample, I'm finding some significant race effects. The effect isn't that large (beta=0.249; non-white having older brains), but I'm presuming a high(er) # of the subs in the classifier are white (so that can be important to consider when running different analyses, etc.). 

Cheers,
Jamie.

**Comment by fliem** [comment]
Thanks for the info Jamie. As the training sample is from Germany it's predominantly white. 
Do you mind sharing a few more characteristics of your sample, for future reference (like age range, ethnicity). Thanks

**Comment by jlhanson5** [comment]
This all makes sense. 

We had ~200 male subjects. Half the subjects were around 26 years of age, while the other half was around 32. In terms of ethnicity, it was a combination of black and white (about 50/50 that spanned the two age cohorts).

**Comment by fliem** [comment]
Thanks. I have added a note and link on the Readme page.
