### ISSUE TITLE
Give possibility not to run FreeSurfer for not segmented subjects

### ISSUE THREAD

**Issue by ntraut** [bids-apps/baracus#12]
Some BIDS datasets can have inconsistencies or FreeSurfer can fail for some subjects. If one run baracus on this kind of dataset, it will try to run FreeSurfer segmentation on unsegmented subjects, but this can be undesirable. I would suggest to add an option to skip this step.

**Comment by fliem** [comment]
How about using the `--participant_label` flag?

**Comment by ntraut** [comment]
That could be a solution but I would also need to select the sessions for each subject. I implemented the option for my personal need but maybe you can keep like that if you think it is OK for the majority.

**Comment by fliem** [comment]
closed by #16
