### ISSUE TITLE
Cortical Surface Area Predictions

### ISSUE THREAD

**Issue by niniko1997** [bids-apps/baracus#4]
We ran the default Baracus model on two different datasets. The Cortical Surface Area age predictions were generally very off. For the first dataset, the Mean Absolute Error was  ~105.02 years for area. The second set we used was from the Human Connectome Project (HCP). The Mean Absolute Error for the HCP data was ~108.87 years for area.

Attached is a CSV File of the area measurements for some HCP subjects and their respective age predictions via aseg, area, thickness and stacked anatomy.

Why do area predictions fare much worse compared to the other three modalities?

[hcp_area.csv.zip](https://github.com/BIDS-Apps/baracus/files/1176772/hcp_area.csv.zip)

**Comment by fliem** [comment]
Did you use the freesurfer data processed by the HCP? AFAIK they tweaked the standard pipeline - might have something to do with that?

**Comment by niniko1997** [comment]
Yeah, for the HCP data, we used the FreeSurfer data they provided. They ran FreeSurfer version 5.3, I believe. But we had the same issue with cortical surface area predictions on our first dataset, where we ran the standard FreeSurfer v 5.3 pipeline ourselves.

**Comment by chrisgorgo** [comment]
Looks like an argument to implement #1 :)

**Comment by fliem** [comment]
Is there anything non-standard about your data? I ran the pipeline with 2 independent datasets & the surface area values looked ok.

**Comment by niniko1997** [comment]
I included a csv file with the area measurements, you can take a look to see if they are very different from the ones produced for your data.

**Comment by fliem** [comment]
I compared your values with another sample (camcan). The values look pretty similar.
Other people that used the pipeline with their data did not report any problems.
Did you run your data with a special freesurfer pipeline, or the standard one?

**Comment by crubb** [comment]
Hey,

same problem here.

We converted a locally acquired Siemens Skyra T1 MP-RAGE DICOM test dataset to BIDS using the current [dcm2niix](https://github.com/rordenlab/dcm2niix/tree/23805db6bb3e0b8d4200339dd7c365ac0f793741) and [bidskit](https://github.com/jmtyszka/bidskit/tree/c9bf6639b7bbd9195dd8671654b4d1589e17e992)'s `dcm2bids.py` on a local box.

We then ran `recon-all` from the 5.3.0HCP-11 release of [BIDS-Apps/freesurfer](https://github.com/BIDS-Apps/freesurfer/releases/tag/v5.3.0HCP-11) and then the current [baracus](https://github.com/BIDS-Apps/baracus/tree/3ed09c92a3dea74c5a4ce05b09b65ba64777f078), both using Docker.

`aseg`, `thickness` and `stacked-anatomy` are ok at ~33-35, the age prediction from `area` is 114.6 years.

Any recommendations? Any logs, which could prove insightful?

Best regards,
-crubb

Edit: Linked the commits of the other repos, as well.

**Comment by crubb** [comment]
I modified https://github.com/BIDS-Apps/freesurfer/releases/tag/v5.3.0HCP-11 to build the standard 5.3.0. Using the non-HCP pipeline, I get accurate predictions for my test dataset.

**Comment by fliem** [comment]
Thanks @crubb for thinking of that.

I have added [documentation](https://github.com/bids-apps/baracus#requirements
) to regarding this issue and linked to a [docker container](https://hub.docker.com/r/fliem/freesurfer/tags/) that can be used for preprocessing.

I will add the preprocessing to the pipeline soon.

**Comment by fliem** [comment]
FYI, I just released a new version that runs freesurfer as part of baracus
